"""PipeWire combine-stream config generation — the engine behind the Share verb.

We build a drop-in for `libpipewire-module-combine-stream` (PipeWire >= 0.3.x, options
validated against the 1.6.x docs). A combine sink fans one playback stream out to
multiple Bluetooth sinks at once ("play on 2").

Key options used (all documented in module-combine-stream):
  combine.mode               = sink            # we expose a virtual sink
  combine.latency-compensate = true            # align per-device latency
  combine.props { }                            # props on the combine node itself
  stream.rules [ { matches=[...] actions={ create-stream={...} } } ]
                                               # which real sinks to fan out to

Per-device latency alignment is delegated to `combine.latency-compensate = true` on the
combine node. module-combine-stream has NO documented per-member latency-offset option,
so the UI latency-sync slider is advisory only for now (NOT wired to a real delay). A true
manual offset would require a per-member loopback filter with node.latency, which this
static drop-in deliberately does not fake.

NOTE: PipeWire config uses braces heavily, so this module assembles the text with plain
string concatenation (no f-string brace escaping) to keep it readable and correct.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

from companion.core import config
from companion.core.models import ShareTarget

_DROPIN_NAME = "combine-stream.conf"

_HEADER = (
    "# Generated by Companion. Safe to delete; edits here may be overwritten.\n"
    '# Engine for "Play on multiple" (Share). Docs: module-combine-stream.\n'
)


def _render_member(target: ShareTarget) -> str:
    """One stream.rules entry that matches a live bluez_output node and joins it.

    BUGFIX: an earlier version wrote `node.latency-offset-nsec` here. That property does
    NOT exist for A2DP combine members — PipeWire only documents `node.latency-offset-msec`
    and only for BLE MIDI nodes. Writing it was a fabricated option that PipeWire ignores at
    best. It has been removed; latency alignment is handled by combine.latency-compensate.
    """
    return (
        "            {\n"
        '                matches = [ { node.name = "' + target.pipewire_node + '" } ]\n'
        "                actions = {\n"
        "                    create-stream = {\n"
        "                        combine.audio.position = [ FL FR ]\n"
        "                        audio.position         = [ FL FR ]\n"
        "                    }\n"
        "                }\n"
        "            }"
    )


def render_combine_stream(targets: Iterable[ShareTarget],
                          sink_name: str = "companion_combine",
                          description: str = "Companion - Play on multiple") -> str:
    """Render a PipeWire drop-in that creates a combine sink fanning out to `targets`."""
    targets = list(targets)
    if not targets:
        raise ValueError("combine-stream needs at least one target sink")

    members = "\n".join(_render_member(t) for t in targets)
    return (
        _HEADER
        + "context.modules = [\n"
        + "    {\n"
        + "        name = libpipewire-module-combine-stream\n"
        + "        args = {\n"
        + "            combine.mode = sink\n"
        + '            node.name    = "' + sink_name + '"\n'
        + '            node.description = "' + description + '"\n'
        + "            combine.latency-compensate = true\n"
        + "            combine.props = {\n"
        + "                audio.position = [ FL FR ]\n"
        + "            }\n"
        + "            stream.props = { }\n"
        + "            stream.rules = [\n"
        + members + "\n"
        + "            ]\n"
        + "        }\n"
        + "    }\n"
        + "]\n"
    )


def apply(targets: Iterable[ShareTarget]) -> Path:
    """Write the combine-stream drop-in atomically and return its path."""
    text = render_combine_stream(targets)
    return config.write_dropin(config.PIPEWIRE_DROPIN, _DROPIN_NAME, text)


def clear() -> bool:
    """Tear down the combine sink (rollback to no-op). Returns True if removed."""
    return config.rollback(config.PIPEWIRE_DROPIN, _DROPIN_NAME)
