"""WirePlumber config generation — codec selection + per-device persistence.

WirePlumber 0.5 uses SPA-JSON `.conf` drop-ins. We write two kinds of settings:

  monitor.bluez.properties  -> global codec enablement / quality defaults
  monitor.bluez.rules       -> per-device overrides matched by device.name

IMPORTANT (Mo2 fix): all per-device rules live in ONE drop-in with a SINGLE
`monitor.bluez.rules = [ ... ]` array. Writing one file per device, each re-declaring
`monitor.bluez.rules`, risks fragments overriding each other rather than merging. We keep
a single merged rules file and rewrite it whenever device rules change.

Keys used are exactly those from the WirePlumber bluetooth config (0.5.x):
  bluez5.enable-sbc-xq, bluez5.enable-msbc, bluez5.enable-hw-volume,
  bluez5.codecs, bluez5.a2dp.ldac.quality, bluez5.a2dp.aac.bitratemode,
  bluez5.auto-connect, node.nick

This is what makes a chosen codec / nickname *stick* across reconnects.
"""
from __future__ import annotations

import logging
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from companion.audio.codecs import AAC_BITRATE_MODE, LDAC_QUALITY, by_key
from companion.core import config

log = logging.getLogger(__name__)
_RELOAD_TIMEOUT = 15.0

_GLOBAL_NAME = "bluetooth.conf"
_RULES_NAME = "device-rules.conf"


@dataclass(frozen=True)
class DeviceRule:
    """A single per-device override. `device_name_glob` matches WirePlumber device.name,
    e.g. ``bluez_card.AA_BB_CC_DD_EE_FF``."""
    device_name_glob: str
    nick: Optional[str] = None
    ldac_quality: Optional[str] = None
    aac_bitratemode: Optional[int] = None
    auto_connect: Optional[bool] = None

    def validate(self) -> None:
        if self.ldac_quality is not None and self.ldac_quality not in LDAC_QUALITY:
            raise ValueError(f"ldac quality must be one of {LDAC_QUALITY}")
        if self.aac_bitratemode is not None and self.aac_bitratemode not in AAC_BITRATE_MODE:
            raise ValueError(f"aac bitratemode must be one of {AAC_BITRATE_MODE}")


def render_global(enabled_codecs: list[str],
                  enable_sbc_xq: bool = True,
                  enable_msbc: bool = True,
                  enable_hw_volume: bool = True) -> str:
    """Render global monitor.bluez.properties with the codec allow-list."""
    for c in enabled_codecs:
        if by_key(c) is None:
            raise ValueError(f"unknown codec token: {c!r}")
    codec_list = " ".join(enabled_codecs)
    return f"""# Generated by Companion. Global Bluetooth codec policy.
monitor.bluez.properties = {{
    bluez5.enable-sbc-xq   = {str(enable_sbc_xq).lower()}
    bluez5.enable-msbc     = {str(enable_msbc).lower()}
    bluez5.enable-hw-volume = {str(enable_hw_volume).lower()}
    bluez5.codecs          = [ {codec_list} ]
}}
"""


def _render_props(rule: DeviceRule) -> str:
    props = []
    if rule.nick is not None:
        props.append(f'                node.nick = "{rule.nick}"')
    if rule.ldac_quality is not None:
        props.append(f"                bluez5.a2dp.ldac.quality = {rule.ldac_quality}")
    if rule.aac_bitratemode is not None:
        props.append(f"                bluez5.a2dp.aac.bitratemode = {rule.aac_bitratemode}")
    if rule.auto_connect is not None:
        props.append(f"                bluez5.auto-connect = {str(rule.auto_connect).lower()}")
    return "\n".join(props) if props else "                # no overrides"


def _render_entry(rule: DeviceRule) -> str:
    return (
        "    {\n"
        '        matches = [ { device.name = "~' + rule.device_name_glob + '" } ]\n'
        "        actions = {\n"
        "            update-props = {\n"
        + _render_props(rule) + "\n"
        "            }\n"
        "        }\n"
        "    }"
    )


def render_rules(rules: list[DeviceRule]) -> str:
    """Render ALL device rules into a single monitor.bluez.rules array (merge-safe)."""
    for r in rules:
        r.validate()
    if not rules:
        body = ""
    else:
        body = "\n" + "\n".join(_render_entry(r) for r in rules) + "\n"
    return "# Generated by Companion. Per-device Bluetooth overrides (merged).\n" \
           "monitor.bluez.rules = [" + body + "]\n"


# Backwards-compatible single-rule helper (used by older call sites / tests).
def render_device_rule(device_name_glob: str,
                       nick: Optional[str] = None,
                       ldac_quality: Optional[str] = None,
                       aac_bitratemode: Optional[int] = None,
                       auto_connect: Optional[bool] = None) -> str:
    return render_rules([DeviceRule(
        device_name_glob=device_name_glob, nick=nick, ldac_quality=ldac_quality,
        aac_bitratemode=aac_bitratemode, auto_connect=auto_connect,
    )])


def apply_global(enabled_codecs: list[str]) -> Path:
    return config.write_dropin(config.WIREPLUMBER_DROPIN, _GLOBAL_NAME,
                               render_global(enabled_codecs))


def apply_rules(rules: list[DeviceRule]) -> Path:
    """Write the single merged per-device rules drop-in."""
    return config.write_dropin(config.WIREPLUMBER_DROPIN, _RULES_NAME,
                               render_rules(rules))


def build_reload_cmd() -> list[str]:
    """Argv that restarts the per-user WirePlumber service so newly written drop-ins
    are picked up (WirePlumber only reads its config at startup)."""
    return ["systemctl", "--user", "restart", "wireplumber"]


def reload() -> bool:
    """Reload WirePlumber so a freshly written codec policy takes effect.

    Returns True on a successful restart, False if systemctl is unavailable or the
    restart failed (the caller then tells the user to reload manually). Never raises.
    """
    cmd = build_reload_cmd()
    if shutil.which(cmd[0]) is None:
        log.info("systemctl not found; cannot auto-reload WirePlumber")
        return False
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=_RELOAD_TIMEOUT)
    except subprocess.SubprocessError:
        log.exception("WirePlumber reload failed")
        return False
    if proc.returncode != 0:
        log.warning("WirePlumber reload exited %d: %s",
                    proc.returncode, (proc.stderr or "").strip())
        return False
    return True
